apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mypizza-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mypizza-statefulset
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50