# Generated by Django 3.2.25 on 2024-07-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('Hawaian', 'Hawaian'), ('Margherita', 'Margherita'), ('Pepperoni', 'Pepperoni'), ('Vegetarian', 'Vegetarian')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
